server:
  port: 9081
spring:
  profiles:
    active: local
  #springmvc 参数策略 2.6.13boot整合springmvc 需要配置的属性
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis:
  mapper-locations: classpath*:mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
#配置调度中心属性
xxl:
  job:
    admin:
      #调度中心连接地址
      addresses: http://127.0.0.1:8080/xxl-job-admin
      #连接调度中心 注册 发送请求 权限票据
    accessToken: default_token
    executor:
      #执行器名称 admin存在一个默认执行器 需要在调度中心注册 需要ip和端口
      appname: warning-info
      address:
      #注册ip 本地就是空
      ip:
      #注册端口 需要和admin通信
      port: 21000
      #日志路径
      logpath: /logs
      #日志保存天数
      logretentiondays: 30


