server:
  port: 9081
spring:
  profiles:
    active: local
  #springmvc 参数策略 2.6.13boot整合springmvc 需要配置的属性
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis:
  mapper-locations: classpath*:mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


